"""Add roles to project_users association

Revision ID: 613c53c96a38
Revises: 
Create Date: 2025-07-01 15:51:41.710003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613c53c96a38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='owner'))

        ### batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
